require 'rails_helper'

# Signed in by the hook in rails_helper, as a reader with no second factor yet — which is what everyone
# is until they set one up.
RSpec.describe 'Setting up two-factor authentication', type: :system do
  let(:user) { signed_in_user }

  def set_it_up
    visit profile_path
    click_link 'Set up an authenticator app'

    # The secret is generated by the screen being asked for, so it has to have arrived before there is
    # one to read.  click_link does not wait for the page it asks for.
    expect(page).to have_css('h1', text: 'Set up two-factor authentication')

    fill_in 'Code from your app', with: ROTP::TOTP.new(user.reload.otp_secret).now
    click_button 'Confirm'
    expect(page).to have_css('h1', text: 'Signing in as')
  end

  it 'starts from the profile screen, which says it is not set up' do
    visit profile_path

    expect(page).to have_css('h1', text: "Signing in as #{user.email_address}")
    expect(page).to have_content('Not set up')
  end

  # Inline SVG rather than an <img>: nothing is fetched, and no file holding a provisioning URI is ever
  # written anywhere to be left behind.
  it 'draws the QR on the page itself' do
    visit new_totp_enrolment_path

    expect(page).to have_css('.qr-code svg', visible: :all)
    expect(page).to have_no_css('.qr-code img')
  end

  it 'offers the secret in words as well, for a device that cannot scan' do
    visit new_totp_enrolment_path

    expect(page).to have_content(user.reload.otp_secret)
  end

  it 'turns the factor on once a code proves the app is set up' do
    set_it_up

    expect(page).to have_css('h1', text: 'Signing in as')
    expect(page).to have_content('Two-factor authentication is on')
    expect(page).to have_content("On since #{user.reload.otp_confirmed_at.to_fs(:short_date)}")
  end

  it 'keeps the same QR when the code is wrong, rather than making the reader scan again' do
    visit new_totp_enrolment_path
    secret = user.reload.otp_secret

    fill_in 'Code from your app', with: '000000'
    click_button 'Confirm'

    expect(page).to have_content('That code was not right')
    expect(page).to have_content(secret)
    expect(user.reload.otp_secret).to eq(secret)
  end

  describe 'turning it off again' do
    before { set_it_up }

    it 'needs the password, and says so when it is wrong' do
      fill_in 'Your password', with: 'not the password'
      accept_confirm { click_button 'Turn off' }

      expect(page).to have_content('That is not your password')
      expect(user.reload).to be_totp_required
    end

    it 'turns it off when the password is right' do
      fill_in 'Your password', with: AuthenticationHelpers::SPEC_PASSWORD
      accept_confirm { click_button 'Turn off' }

      expect(page).to have_content('Not set up')
      expect(user.reload).not_to be_totp_required
    end
  end
end
